services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile-php
    volumes:
      - ./src:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./logs:/var/log
    expose:
      - "9000"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile-nginx
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    ports:
      - "5432:5432"

volumes:
  pgdata:
